### ISSUE TITLE
MMUIrisDatabase

### ISSUE THREAD

**Issue by tineo** [19hgp-es/iris_processing#1]
The link http://www.cs.princeton.edu/~andyz/downloads/MMUIrisDatabase.zip is broken

**Comment by PineApple777** [comment]
Do you want Iris Datasets?
The Dataset is **Multimedia University Iris Datasets**, but This dataset just get from our lab researchers.
Maybe, you can research that database at google, but University does not open that iris database.
I recommend use another iris database, like CASIA-Iris-Dataset, which link is here [http://www.cbsr.ia.ac.cn/english/IrisDatabase.asp](http://www.cbsr.ia.ac.cn/english/IrisDatabase.asp)
sorry for that, bro.

**Comment by tineo** [comment]
No problem, I'd like to try it  with original dataset.
I have another but it didn't work well

**Comment by PineApple777** [comment]
Maybe, if you use Eye images like upper that datasets, I think you might be modify Iris inside Eyes.
example like rotate, rgb color enhances, or change shapes.
I think this is the best I can tell you. :) you can do that bro. 👍
